CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    icon_url VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tech_stacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    version VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    field_id BIGINT,
    icon_url VARCHAR(255),
    registry_type VARCHAR(255),
    registry_identifier VARCHAR(255),
    registry_auto_sync BOOLEAN NOT NULL DEFAULT TRUE,
    registry_last_synced_at TIMESTAMPTZ,
    registry_last_sync_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tech_stack_field FOREIGN KEY (field_id) REFERENCES fields (id)
);

CREATE TABLE dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(100) NOT NULL UNIQUE,
    tech_stack_id BIGINT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    version VARCHAR(255),
    is_recommended BOOLEAN NOT NULL,
    document_url VARCHAR(255),
    registry_type VARCHAR(255),
    registry_identifier VARCHAR(255),
    registry_auto_sync BOOLEAN NOT NULL DEFAULT TRUE,
    registry_last_synced_at TIMESTAMPTZ,
    registry_last_sync_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dependency_tech_stack FOREIGN KEY (tech_stack_id) REFERENCES tech_stacks (id)
);

CREATE TABLE field_stack_mappings (
    field_id BIGINT NOT NULL,
    tech_stack_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (field_id, tech_stack_id),
    CONSTRAINT fk_field_stack_mapping_field FOREIGN KEY (field_id) REFERENCES fields (id),
    CONSTRAINT fk_field_stack_mapping_tech_stack FOREIGN KEY (tech_stack_id) REFERENCES tech_stacks (id)
);

CREATE TABLE catalog_registry_versions (
    target_type VARCHAR(255) NOT NULL,
    target_id BIGINT NOT NULL,
    version VARCHAR(255) NOT NULL,
    is_latest BOOLEAN NOT NULL,
    is_stable BOOLEAN NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (target_type, target_id, version)
);

CREATE TABLE projects (
    project_id UUID NOT NULL PRIMARY KEY,
    user_id BIGINT,
    project_name VARCHAR(50) NOT NULL,
    description VARCHAR(500),
    structure JSONB,
    status VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_project_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE project_fields (
    project_id UUID NOT NULL,
    field_id BIGINT NOT NULL,
    PRIMARY KEY (project_id, field_id),
    CONSTRAINT fk_project_field_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_project_field_field FOREIGN KEY (field_id) REFERENCES fields (id)
);

CREATE TABLE project_tech_stacks (
    project_id UUID NOT NULL,
    tech_stack_id BIGINT NOT NULL,
    version VARCHAR(255),
    PRIMARY KEY (project_id, tech_stack_id),
    CONSTRAINT fk_project_tech_stack_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_project_tech_stack_tech_stack FOREIGN KEY (tech_stack_id) REFERENCES tech_stacks (id)
);

CREATE TABLE project_dependencies (
    project_id UUID NOT NULL,
    dependency_id BIGINT NOT NULL,
    version VARCHAR(255),
    PRIMARY KEY (project_id, dependency_id),
    CONSTRAINT fk_project_dependency_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_project_dependency_dependency FOREIGN KEY (dependency_id) REFERENCES dependencies (id)
);

CREATE TABLE structure_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id UUID NOT NULL,
    type VARCHAR(20) NOT NULL,
    path VARCHAR(1000) NOT NULL,
    depth INTEGER NOT NULL,
    content TEXT,
    language VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_structure_files_project_path UNIQUE (project_id, path)
);
